### ISSUE TITLE
一直显示“标点模型载入中”

### ISSUE THREAD

**Issue by tony2015116** [HaujetZhao/CapsWriter-Offline#108]
![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/26536471/d107b24b-9db0-487e-9fb1-0d8cf8d7516a)

**Comment by dreamking60** [comment]
你的标点模型只会显示载入中吗，哪怕等了五分钟也是这样子吗？

**Comment by tony2015116** [comment]
好了，开始等了好久，终于可以使用了
