### ISSUE TITLE
win7使用客户端

### ISSUE THREAD

**Issue by 871052165** [HaujetZhao/CapsWriter-Offline#12]
WIN7（py3.8）下使用客户端会出现无法录音的情况，按下大写锁定无反应，WIN10正常，大佬是否可以帮忙打包一个WIN764的客户端

**Comment by HaujetZhao** [comment]
onnxruntime 无法在 Win7 上面运行，服务端是肯定无法运行在 win7 上面的。

客户端我也不确定能否使用，这个需要你实测一下安装客户中所需要的依赖后，能否在 win7 上面运行源代码使用？

**Comment by HaujetZhao** [comment]
今天打包了新版，包含了 Windows7 可用的客户端了。
