### ISSUE TITLE
feature request: Android support

### ISSUE THREAD

**Issue by ivysrono** [HaujetZhao/CapsWriter-Offline#13]
无论是独立APP还是Rime等的输入方案，技术上能否实现？毕竟移动端实现的需求显然高于PC端。

**Comment by HaujetZhao** [comment]
我记得几年前问过 rime 作者关于集成语音输入，调用第三方 api，但作者回复说对语音输入不感兴趣。

我个人是没有能力写一个移动端语音输入法的。
