### ISSUE TITLE
请问能否更换录音方法呢？

### ISSUE THREAD

**Issue by milk-Dark** [HaujetZhao/CapsWriter-Offline#15]
目前是输入需要一直按着capslk录音，松开结束录音。但是如果一段话有点长，一直按着比较不方便。
因此能否改为，连点两下capslk开始录音，再连点两下结束录音呢？
谢谢大佬😙

**Comment by ShiTieSeng** [comment]
大佬暂时不考虑做，不过我找到了一个曲线方法，可以用Quicker来实现，quicker设置-扩展热键或者按键双击-新建一个动作-操作类型选择键鼠控制，然后填入你的录音键按下或者抬起的指令，比如我的是NumLock，就是20;	KD;	NumLock;（按下），20;	KP;	NumLock;（抬起）。

**Comment by ShiTieSeng** [comment]
这样的话，触发的方式可以自由选择，可以鼠标按键、鼠标手势、鼠标圆盘、快捷键、单按键、按键双击，几乎所有的触发方式
