### ISSUE TITLE
这个离线版，每次识别结果都会弄一份到剪贴板吗？

### ISSUE THREAD

**Issue by noteaplz** [HaujetZhao/CapsWriter-Offline#18]
在我这里是这样的，每句话识别结果都会在剪贴板里占一条，导致我的第三方剪贴板工具就被事实上占领瘫痪了。

作者大大在线版本并没有这个问题。

请问是设计如此，还是我自己这边有什么个别原因导致个别问题呢？

![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/32857069/5fe85586-3db1-45b5-aaac-7c18b168a04f)

![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/32857069/e89864f8-ec73-4e08-93bc-52bb3de8464a)

**Comment by HaujetZhao** [comment]
这是为了快速输入。可以编辑 core_client.py 改变这个行为。
