### ISSUE TITLE
[Feature Request] Awsome Application! Could You Please Add a Docker Version of it When You Have Spare Time? 

### ISSUE THREAD

**Issue by fairyex** [HaujetZhao/CapsWriter-Offline#2]
So I can install it on my NAS and every device in local network could easily access it, save tons of space and power.

**Comment by Jillian37** [comment]
我觉得挺好~支持有一个docker版本,本地只需要运行client 就好了

**Comment by shandianchengzi** [comment]
> So I can install it on my NAS and every device in local network could easily access it, save tons of space and power.

> 我觉得挺好~支持有一个docker版本,本地只需要运行client 就好了

我现在就是把模型放到NAS上的，需要安装的依赖貌似只有 python 相关的，确实本地只需要启动 client，运行着挺正常的诶。似乎没有必要为了服务器部署做一个 docker。
