### ISSUE TITLE
被360拦截了

### ISSUE THREAD

**Issue by YeabutY** [HaujetZhao/CapsWriter-Offline#21]
类型:木马-HEUR/QVM202.0.998A.Malware.Gen
描述:木马是一种伪装成正常文件的恶意软件，会盗取您的帐号、密码等隐私资料。
扫描引擎:云特征引擎
文件路径:D:\插件\CapsWriter-Offline\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\start_client.exe
文件大小:338.4K (346,540 字节)
文件指纹（MD5）:0079a4538495fc9b1903cfc81670f558
处理建议:隔离文件

这是正常的吗？还是下载过程被感染了

**Comment by HaujetZhao** [comment]
360不干人事
