### ISSUE TITLE
新版的标点符号模型，载入时间是原来老模型的2.5倍，请问是否正常？

### ISSUE THREAD

**Issue by francofang** [HaujetZhao/CapsWriter-Offline#27]
我是Windows 10系统，更新了最新的版本和模型。
我注意到新版的标点符号模型，载入时间，是原来的2.5倍。老版载入需要20秒，新版需要50秒。
请问是否正常？

**Comment by HaujetZhao** [comment]
非常的正常，因为换用了更大的标点模型，载入时间变长了，但是标点符号能力更强更准确了。

**Comment by HaujetZhao** [comment]
今天刚出了 Windows 打包版本，可以在 releases 界面和百度网盘里下载了。

**Comment by francofang** [comment]
非常感谢

**Comment by francofang** [comment]
64bit，windows打包文件里，config.py里面默认把format_punc引擎给关了。我自己改过来才正常输出了标点符号。

class ServerConfig:
    addr = '0.0.0.0'
    port = '6016'

    format_num = True  # 输出时是否将中文数字转为阿拉伯数字
    format_punc = False  # 输出时是否启用标点符号引擎（在 MacOS 上标点引擎似乎有问题，应当改为 False）
    format_spell = True  # 输出时是否调整中英之间的空格

**Comment by HaujetZhao** [comment]
改过来了
