### ISSUE TITLE
Could not setup clipboard

### ISSUE THREAD

**Issue by MotWnb** [HaujetZhao/CapsWriter-Offline#28]
Could not setup clipboard
![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/98505614/07f6b8c9-7056-4642-ba4e-607c6a2120f1)

**Comment by MotWnb** [comment]
一台电脑正常，这台就不行，什么问题

**Comment by HaujetZhao** [comment]
什么环境？

**Comment by MotWnb** [comment]
Win10 64位 Python3.10.11
我是git clone的，release的没这个问题

**Comment by HaujetZhao** [comment]
用虚拟环境试试

**Comment by MotWnb** [comment]
解决了，把client_type_result的pyclip改成pyperclip就行了

**Comment by MotWnb** [comment]
![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/98505614/d5fce7ce-f8e9-495b-871a-6fd5d981df84)

**Comment by H1DDENADM1N** [comment]
我刚也遇到了，真怪

**Comment by HaujetZhao** [comment]
Linux on X11 requires xclip to work. Install with your package manager, e.g. sudo apt install xclip Linux on Wayland requires wl-clipboard to work. Install with your package manager, e.g. sudo apt install wl-clipboard

**Comment by MotWnb** [comment]
我Windows



---- Replied Message ----
| From | Haujet ***@***.***> |
| Date | 01/22/2024 21:31 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [HaujetZhao/CapsWriter-Offline] Could not setup clipboard (Issue #28) |

Linux on X11 requires xclip to work. Install with your package manager, e.g. sudo apt install xclip Linux on Wayland requires wl-clipboard to work. Install with your package manager, e.g. sudo apt install wl-clipboard
