### ISSUE TITLE
docker服务端

### ISSUE THREAD

**Issue by TianMiao8152** [HaujetZhao/CapsWriter-Offline#29]
大佬有没有计划建立一个docker服务端

**Comment by HaujetZhao** [comment]
没计划

**Comment by TianMiao8152** [comment]
那我可以进行docker版本的开发吗

**Comment by HaujetZhao** [comment]
我还不会用 docker，也用不到，暂时不想加新功能了，可能等过上一两年买上独显电脑，加入显卡加速。在此之前就想保持不动。

如果你想的话，可以 fork 一个做做。

**Comment by SIPC** [comment]
> 那我可以进行docker版本的开发吗

我看你这边没啥动静，顺手捏了一个（
https://github.com/SIPC/CapsWriterOffline-DockerServer

**Comment by TianMiao8152** [comment]
> > 那我可以进行docker版本的开发吗
> 
> 我看你这边没啥动静，顺手捏了一个（ https://github.com/SIPC/CapsWriterOffline-DockerServer

最后一周期末考试啦，下个周末才有时间
老哥整的挺快，那我不需要弄了吧(哭笑)

**Comment by SIPC** [comment]
> @SIPC Hi! Thank you for creating the Docker version 2 years ago! I noticed the repository hasn't been updated since then. Would you consider updating the Docker image with the latest version of CapsWriter-Offline? It would be really helpful for users who prefer Docker deployments. Thanks!

I just saw it now! I will find time to pack the new version soon!

**Comment by shawn8888** [comment]
> I just saw it now! I will find time to pack the new version soon!

@SIPC  Any update on this, please?
