### ISSUE TITLE
文件名或扩展名过长

### ISSUE THREAD

**Issue by qaq1000w** [HaujetZhao/CapsWriter-Offline#45]
向客户端拖入大量音频文件导致错误

![Screenshot_2024-01-16-23-28-24-122_com carriez flutter_hbb](https://github.com/HaujetZhao/CapsWriter-Offline/assets/80654352/a37a604f-a270-4057-bf10-b0f4af7a0ba5)
![Screenshot_2024-01-16-23-30-37-066_com carriez flutter_hbb](https://github.com/HaujetZhao/CapsWriter-Offline/assets/80654352/0679f75d-c379-4a1b-bfb6-e758648acead)

**Comment by HaujetZhao** [comment]
感觉不是客户端的问题，是系统本身的限制，无法传递太长的参数。建议写个 bat 批处理，调用 core_client.py ，给批处理拖入文件夹，递归处理文件夹内的 wav 文件。

客户端倒如果要写处理拖入文件夹，问题会是，应当处理哪些后缀名的文件。所以建议还是自己写个遍历文件夹内文件的 bat 脚本。
