### ISSUE TITLE
请教 其他程序需要读取客户端返回的内容，有没有接口

### ISSUE THREAD

**Issue by gaoyuoppa** [HaujetZhao/CapsWriter-Offline#64]
如果我需要获取客户端的到的文字结果，可不可以增加一个接口，比如增加对客户端增加一个ws端口让第三方程序可以读取呢

**Comment by HaujetZhao** [comment]
我暂时没需求，懒得动代码。

**Comment by gaoyuoppa** [comment]
好的，谢谢，前先用临时写文件来代替了
\util\client_type_result.py 文件把模拟打印替换为写文件

**Comment by gaoyuoppa** [comment]
哦哦，WS也可以了，报错是缩进行的问题。    折腾好久，原来Py对缩进行要求这吗严格。
        uri = "ws://127.0.0.1:XXXXX"
    try:
        async with websockets.connect(uri) as websocket:
            await websocket.send(text)

    except Exception as e:
        print(f"连接失败： {e}")
