### ISSUE TITLE
直播实时字幕 我的解决办法

### ISSUE THREAD

**Issue by gaoyuoppa** [HaujetZhao/CapsWriter-Offline#65]
提供我目前的解决办法/思路，修改按键映射为两秒一循环，缺点就是，意外的断点识别不准确，但是实时字幕是影响不大的。
关于字符串提供，原程序提供模拟输入和剪辑版，我的解决办法是，写到指定txt和ws协议（推荐）输出给你的程序。

只需要修改  \util 下的 就可以了，
client_shortcut_handler.py
client_type_result.py

**Comment by gaoyuoppa** [comment]
提供下自己的思路，我自己关闭啦，由于改动很简单，如果有人需要，可以留言，我看到回复。

**Comment by QWXL** [comment]
我一开始的想法是通过node.js的child process功能，捕获进程的控制台输出，以此取得识别的文字，这个思路倒是没想过，主要是没打算大改代码
