### ISSUE TITLE
能否在识别英文时将首字母大写，并且将标点符号转为英文半角

### ISSUE THREAD

**Issue by PeterFan2008** [HaujetZhao/CapsWriter-Offline#72]

**Comment by HaujetZhao** [comment]
前者不想做。后者可以在 `hot-rule.txt` 中添加正则规则实现。

**Comment by GaoYuan522** [comment]
> 前者不想做。后者可以在 `hot-rule.txt` 中添加正则规则实现。

能否通过添加hot-rule实现？

**Comment by HaujetZhao** [comment]
> 能否通过添加hot-rule实现？

python 的正则替换没有转换大小写功能

**Comment by GaoYuan522** [comment]
> > 能否通过添加hot-rule实现？
> 
> python 的正则替换没有转换大小写功能

好的谢谢您！
