### ISSUE TITLE
bug＆建议：建议基于本模型开发语音助手和大模型的功能。bug：当你按住大写锁定，然后不说话，它会生成一些类似应付的语句。当你跟他说一次话之后，再次录音，然后不说话，他的回复好像是在跟你聊天，但是不太成熟。

### ISSUE THREAD

**Issue by GaoYuan522** [HaujetZhao/CapsWriter-Offline#75]
我真的感觉他在和我聊天，所以要不然顺带手开发一个基于本模型的语音助手和大模型功能吧！

亲测示例：
我： are you ok？
它（我的环境绝对安静，按住不说话）：对对对对。
我：你还好吗？
它：对的对的，你的那个。
我：你是谁？
它：是的是的，是有没有意有。
我：等会儿这是聊天吗？
它：好的，对的。
我：我觉得你在说笑。
它：我是一个的一个。
我：你知道我是谁吗？
它：嗯，是不是？

……

**Comment by HaujetZhao** [comment]
这是模型的幻觉，你硬要让模型从充满环境噪音的静音片段转录文字，就会有这种现象

**Comment by GaoYuan522** [comment]
> 这是模型的幻觉，你硬要让模型从充满环境噪音的静音片段转录文字，就会有这种现象

感谢您的耐心回答，其实我想说的就是这个意思。如果没有输入的话，模型会不会吐出一些训练数据？类似于ChatGPT前阵子的漏洞一样。

**Comment by qhgy** [comment]
这个有办法避免吗？
