### ISSUE TITLE
建议把所有的分支（包括语音识别，语音翻译和GUI）都整合到master里面，打包之后方便一起使用。下载的translator里面没有start.exe 

### ISSUE THREAD

**Issue by GaoYuan522** [HaujetZhao/CapsWriter-Offline#78]

**Comment by H1DDENADM1N** [comment]
是说我的CapsTransfer分之吗？ 同时启动服务端和客户端的start.exe是故意去除未打包的，原因：https://github.com/HaujetZhao/CapsWriter-Offline/pull/53#issuecomment-1903681063

**Comment by H1DDENADM1N** [comment]
是说我的CapsTransfer分支吗？ 同时启动服务端和客户端的start.exe是故意去除未打包的，原因：https://github.com/HaujetZhao/CapsWriter-Offline/pull/53#issuecomment-1903681063

**Comment by GaoYuan522** [comment]
> 是说我的CapsTransfer分支吗？ 同时启动服务端和客户端的start.exe是故意去除未打包的，原因：https://github.com/HaujetZhao/CapsWriter-Offline/pull/53#issuecomment-1903681063

辛苦！我了解了，感谢您的耐心回复！

**Comment by GaoYuan522** [comment]
> 是说我的CapsTransfer分支吗？ 同时启动服务端和客户端的start.exe是故意去除未打包的，原因：https://github.com/HaujetZhao/CapsWriter-Offline/pull/53#issuecomment-1903681063

祝您以后的开发更加顺利！
