### ISSUE TITLE
我使用过程中，实时修改了热词txt，然后语音输入就不能识别了。

### ISSUE THREAD

**Issue by francofang** [HaujetZhao/CapsWriter-Offline#8]
我使用过程中，实时修改了热词txt文件，中英文的都修改了。
然后语音输入就不能识别了，所有的语音都只能识别成“hello,好的好的好的好的”之类的。
我重启和重新安装了软件，都没有效果，不知道是哪里出了问题。

**Comment by HaujetZhao** [comment]
看起来像是麦克风问题，没有录到声音，或者录到杂音，就会使这样。用录音机软件检查下麦克风能不能正常用，再检查下默认麦克风是哪个。

**Comment by francofang** [comment]
啊，确实是。不知为什么系统换了一个离线的蓝牙耳机做默认麦克风。
谢谢作者这样实时解答疑难！
