### ISSUE TITLE
建议可以通过计算机名识别服务端与客户端。这样，如果服务端和客户端不在同一局域网内，也无需更改config.py，只需切换局域网寻找连接。

### ISSUE THREAD

**Issue by GaoYuan522** [HaujetZhao/CapsWriter-Offline#81]
比如家里有多个区域网或公司有多个区域网的地方，无法保证服务端和客户端总是处在同一区域网内，这时候就需要通过识别计算机名的方式，这样更方便快捷。或者干脆添加一个全自动扫描功能，如果本局域网内没有扫描到服务端，则请求切换局域网。

**Comment by HaujetZhao** [comment]
我不只是作者，也是软件的第一客户，所有功能的开发与否，只有一个标准，即「我是否需要，我是否会用到」。

在我的需求中，软件的首要目标，是在一台笔记本上实现运行，一般情况下不需要另外一台服务器机器。除非是不得以，运行的机器是 win7，才要找外援。

只是服务端、客户端分离，提供了在不同机器上运行服务端这样一种方法，但它不是主要 feature，不在我的主要使用场景中，所以这个功能我不会做的。
