### ISSUE TITLE
请您出一期hot-rule使用教程，辛苦

### ISSUE THREAD

**Issue by GaoYuan522** [HaujetZhao/CapsWriter-Offline#86]
简单规则会使用，稍微复杂点就蒙圈了，比如事例中给的关于`@\2.\4`的规则就看不太懂🤣

**Comment by GaoYuan522** [comment]
正则表达式是通用的吗？~~我不太懂~~

**Comment by GaoYuan522** [comment]
好吧是通用的🤣🤣🤣
【正则表达式教程【完整版】-哔哩哔哩】 https://b23.tv/6K5bQQc

**Comment by HaujetZhao** [comment]
你可以在这几个在线工具中试验一下：

- [regex101: build, test, and debug regex](https://regex101.com/) 
- [Debuggex: Online visual regex tester. JavaScript, Python, and PCRE.](https://www.debuggex.com/?flavor=javascript) 
- [Regular-Expressions.info - Regex Tutorial, Examples and Reference - Regexp Patterns](https://www.regular-expressions.info/)
