### ISSUE TITLE
在linux mint下安装client时候报错

### ISSUE THREAD

**Issue by francofang** [HaujetZhao/CapsWriter-Offline#9]
在linux mint下安装client时候报错：
pip install -r requirements-client.txt  -i https://mirror.sjtu.edu.cn/pypi/web/simple
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirements-client.txt'

**Comment by HaujetZhao** [comment]
你是不是还没进到项目目录里面就执行这个命令了
