### ISSUE TITLE
centos 7 虚机，无cuda和gpu，服务端标点模型载入正常，客户端是win10，语音输入后没有一个标点

### ISSUE THREAD

**Issue by gongqf** [HaujetZhao/CapsWriter-Offline#94]
**虚机里的服务端载入标点模型正常，但是语音输入后没有一个标点：**
当前基文件夹：/home/CapsWriter-Offline/CapsWriter-Offline-1.0

绑定的服务地址：0.0.0.0:6016

模块加载完成

语音模型载入完成

标点模型载入完成

模型加载耗时 55.85s

───────────────────────────────────────────────────────────────────────── 开始服务 ─────────────────────────────────────────────────────────────────────────

接客了：<websockets.legacy.server.WebSocketServerProtocol object at 0x7f6afbf7f790>

接客了：<websockets.legacy.server.WebSocketServerProtocol object at 0x7f6afbfd4c40>

识别结果：
    按人工费去运维吗
识别结果：
    就把那个光缆上的数字挑挑开嘛挑不开就把它那个呃砍砍断嘛处理一下按工时费计算嘛几工嘛

**win10 里的服务端载入标点模型正常，语音输入标点也正常**
当前基文件夹：E:\install\CapsWriter-Offline\CapsWriter-Offline-Windows-64bit

绑定的服务地址：0.0.0.0:6016

模块加载完成

语音模型载入完成

标点模型载入完成

模型加载耗时 34.12s

────────────────────────────────────────────────────── 开始服务 ───────────────────────────────────────────────────────

接客了：<websockets.legacy.server.WebSocketServerProtocol object at 0x000001A97FFAC940>

识别结果：
    就是把光缆上的树枝挑挑开，挑不开，就把那个树枝砍断处理一下，按工时计费算工时。

**Comment by HaujetZhao** [comment]
测试一下这个脚本的效果：  models/模型测试/03-01-标点模型测试.py

**Comment by gongqf** [comment]
`(CapsWriter-Offline) [root@localhost 模型测试]# python 03-01-标点模型测试.py
正在载入模型
.onnx is not exist, begin to export onnx
Traceback (most recent call last):
  File "/home/venv/CapsWriter-Offline/lib/python3.10/site-packages/funasr_onnx/punc_bin.py", line 51, in __init__
    from funasr.export.export_model import ModelExport
ModuleNotFoundError: No module named 'funasr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/CapsWriter-Offline/CapsWriter-Offline-1.0/models/模型测试/03-01-标点模型测试.py", line 12, in <module>
    model = CT_Transformer(model_dir, quantize=True)
  File "/home/venv/CapsWriter-Offline/lib/python3.10/site-packages/funasr_onnx/punc_bin.py", line 53, in __init__
    raise "You are exporting onnx, please install funasr and try it again. To install funasr, you could:\n" \
TypeError: exceptions must derive from BaseException
`

funasr-onnx              0.2.4

**Comment by HaujetZhao** [comment]
放到标点符号模型文件夹中运行

**Comment by gongqf** [comment]
(CapsWriter-Offline) [root@localhost punc_ct-transformer_cn-en]# python 03-01-标点模型测试.py
正在载入模型
载入模型时间：59.23414206504822


请输入多行文字，按下回车键完成输入:
对于这个跑步观念不一致应该这么看，有些人明知抽烟喝酒不健康增加疾病风险，但是就是改不了。至少跑步、爬山好一点，能带来心肺功能提升、精神状态改善、压力的释放等等，形成一个爱好了后，就有了追求目标。尽量能合理科学的进行运动，这是我的目的。

对于这个跑步观念不一致，应该这么看。，有些人明知抽烟喝酒不健康，增加疾病风险。，。但是就是改不了。，至少跑步、爬山好一点。，能带来心肺功能，提升、精神状态、改善、压力的释放等等。，形成一个爱好了后，，就有了追求目标。。尽量能合理科学的进行运动。，，这是我的目的。。


请输入多行文字，按下回车键完成输入:
对于这个跑步观念不一致应该这么看有些人明知抽烟喝酒不健康增加疾病风险但是就是改不了至少跑步爬山好一点能带来心肺功能提升精神状态改善压力的释放等等形成一个爱好了后就有了追求目标尽量能合理科学的进行运动这是我的目的

对于这个跑步观念不一致，应该这么看。有些人明知抽烟喝酒不健康，增加疾病风险，但是就是改不了。至少跑步爬山好一点，能带来心肺功能，提升精神状态、改善压力的释放等等，形成一个爱好了。后就有了追求目标，尽量能合理科学的进行运动，这是我的目的。


请输入多行文字，按下回车键完成输入:

**Comment by HaujetZhao** [comment]
那这只能一步步调试服务端了，我暂时做不了。

**Comment by gongqf** [comment]
服务端有相关log功能吗？可以传上来
在服务端界面看起来都载入正常了

**Comment by HaujetZhao** [comment]
没做 log ，手动用 vscode 断点测试吧

**Comment by gongqf** [comment]
![Snipaste_2024-02-27_14-36-46](https://github.com/HaujetZhao/CapsWriter-Offline/assets/751931/3168dab5-8bdd-4fd4-a94c-93fc871d4477)
搞定了vscode环境，但不清楚如何调试，请指点
