### ISSUE TITLE
功能请求：仅当触发shortcut时，打开麦克风

### ISSUE THREAD

**Issue by Mingzefei** [HaujetZhao/CapsWriter-Offline#97]
我的蓝牙耳机会在麦克风打开时屏蔽输出。
这样，在启动start_client.exe时，蓝牙耳机仅能用作麦克风，而损失了语音播放的功能。
能否将现在的**保持麦克风打开**，改为**仅触发shortcut时打开麦克风**？

**Comment by H1DDENADM1N** [comment]
🤩有趣的想法，拿走了，

已实现 [新增 支持 只在按下录音快捷键时启用麦克风](https://github.com/H1DDENADM1N/CapsWriter-Offline/commit/3187fd6579d918c79c8114163348e6bc6514f099)

已打包发布 https://github.com/H1DDENADM1N/CapsWriter-Offline/releases/tag/gui-v1.1.3

> 默认启用，通过 `config.py` 中 `Only_enable_microphones_when_pressed_trans_shortcut` 配置。建议启用，有些蓝牙耳机录音时无法播放。而且启用后，切换默认麦克风也不用重启客户端，比如从蓝牙耳机换回笔记本电脑默认麦克风。缺点就是输入的时候可能会慢些，毕竟要先建立与麦克风的连接

> ![只在按下录音快捷键时启用麦克风](https://github.com/H1DDENADM1N/CapsWriter-Offline/assets/65646535/8032a7bd-c498-4207-b69c-ee8515c402de)

@HaujetZhao  感觉这个功能挺实用的，希望你这边也能增加支持

**Comment by HaujetZhao** [comment]
启动麦克风有巨大延迟，会导致大约前 0.5 秒的语音无法被录制到，这是不可接受的。

你能接受每次按下快捷键，等他一会才能说话吗？

**Comment by H1DDENADM1N** [comment]
> 你能接受每次按下快捷键，等他一会才能说话吗？

我把它写在了 config 可选配置项，需要用耳机时启用，还是挺方便的

**Comment by HaujetZhao** [comment]
同时，不建议使用蓝牙耳机麦克风，会有额外的约 0.8 秒的末端延迟，即，你需要说完后等上 0.8 秒，再松开按键，才能保证你说的话被录全了。

**Comment by HaujetZhao** [comment]
@H1DDENADM1N  CapsWriter 阿里云在线版第一个版本我就是用时开麦，但发现有巨大延迟，才改用持续开麦的。

**Comment by H1DDENADM1N** [comment]
延迟确实感人，但对于蓝牙耳机用户，也只能这样了

**Comment by Mingzefei** [comment]
这个延迟可能和硬件相关很大，可以把这个选项开放给用户，让用户自己选择。

**Comment by H1DDENADM1N** [comment]
> 这个延迟可能和硬件相关很大，可以把这个选项开放给用户，让用户自己选择。

我写的就是把是否启用此功能开放给用户的

**Comment by HaujetZhao** [comment]
很抱歉，这个功能我不会加，有点独裁，但我认为会吃灰的功能都不加。

后面我再想想有没有别的更好地无线接收录音的方法。

**Comment by H1DDENADM1N** [comment]
> 很抱歉，这个功能我不会加，有点独裁，但我认为会吃灰的功能都不加。
> 
> 后面我再想想有没有别的更好地无线接收录音的方法。

哈哈哈没什么独裁，开源的一大好处就是需要的人可以自己更改增加自己想要的功能

**Comment by HaujetZhao** [comment]
嗯对。有兴趣的人自己加就行了。我对这软件各方面的需求已经都满足了。

许多功能，理论上是有用，可一想想，对于正常的使用，并没有显著的提升。

我就是想打开他，拖到个虚拟桌面里，然后就能低延迟地语音输入，输出结果最好能用自定义的正则表达式做一下替换，这就够了。

至于开机启动，快捷方式放到启动文件夹就行，至于 GUI，除了把它拖到虚拟桌面里，其它时间我都见不到这软件界面的，做了就跟没做一样。

目前唯一想做还没做的就是加入 whisper 多语言支持，不过毕竟母语中文，没那么急，等以后买上独显电脑再弄。

**Comment by Mingzefei** [comment]
好的，我关闭这个issue。
